### ISSUE TITLE
关于酸奶云套餐价格调整的讨论

### ISSUE THREAD

**Issue by kallydev** [kallydev/yogurt-cloud#2]
# 关于酸奶云套餐价格调整

以往的服务器已很难再支撑目前的用户规模，我需要提供更高的带宽以及硬件配置

## 我的目的

- 提升所有节点的带宽到最低 1 Gbps
- 让所有节点支持流媒体服务
- 对长期表现不良的移动网络提供优化
- 不盲目的追求节点数量，但尽可能为不同的地区做扩展
- 套餐面向单人和多人两种，但具体策略不同

## 已经准备：

- 调查其他主流服务商的价格
- 对前期准备一笔可观的资金投入

## 注意事项

- 我们的资金状况没有出现问题，但提高质量需要至少等比的资金收入
- 目的并不是为了追求极致的速度，让服务稳定的同时且流畅才是目的
- 不与低价超卖的服务商作对比，他们的用户基数远大于成本，毕竟一分钱一分货

> 在此可以说出真实想法，无需顾忌

**Comment by ysd1123** [comment]
> 套餐面向单人和多人两种，但具体策略不同 

这个具体策略大概是什么样的呢？

**Comment by kallydev** [comment]
> 这个具体策略大概是某种的呢？

之前个人用户一直不限制数据量，我想延续这种模式。但考虑到部分使用量较低的用户，可以让他们一起合租一个有使用量限制的订阅。每个人都是不同的账号，但使用量都整合到一个套餐内。

**Comment by ysd1123** [comment]
> > 这个具体策略大概是某种的呢？
> 
> 之前个人用户一直不限制数据量，我想延续这种模式。但考虑到部分使用量较低的用户，可以让他们一起合租一个有使用量限制的订阅。每个人都是不同的账号，但使用量都整合到一个套餐内。

~~像我这样~~本来就看中原来低价的学生党肯定是希望有个低配套餐的，不怎么看剧只看网页，1Gbps真的太多...上学的话也许只有周末偶尔码个代码，平时月流量是真的不大。

**Comment by kallydev** [comment]
> ~像我这样~本来就看中原来低价的学生党肯定是希望有个低配套餐的，不怎么看剧只看网页，1Gbps真的太多...上学的话也许只有周末偶尔码个代码，平时月流量是真的不大。

合租的模式或许适合你，我认为目前的转型期间套餐购买总量比用户总量更重要

**Comment by ysd1123** [comment]
那kally打算提价后的价格大概在多少呢，我Google了一下，你这种模式的机场好像挺少的。

**Comment by kallydev** [comment]
> 那kally打算提价后的价格大概在多少呢，我Google了一下，你这种模式的机场好像挺少的。

目前的想法是最基础的套餐月付 30，具体的策略还得讨论一下

**Comment by ysd1123** [comment]
> 目前的想法是最基础的套餐月付 30，具体的策略还得讨论一下

听起来挺香的，如果是1gbps+无限流量的话，虽然我不需要这么大带宽（

**Comment by ysd1123** [comment]
> 目前的想法是最基础的套餐月付 30，具体的策略还得讨论一下

最基础？是打算分出不同配置的各种套餐吗？

**Comment by kallydev** [comment]
> 听起来挺香的，如果是1gbps+无限流量的话，虽然我不需要这么大带宽（

这个套餐对标的是每 GB 为 0.1 元，差不多是主流机场的中位数，然而前期收入依然不可观

**Comment by kallydev** [comment]
> 最基础？是打算分出不同配置的各种套餐吗？

不确定会不会提供月付套餐，可能会从季付开始。还是区分个人用户和多人用户，前期就不打算出其他的套餐，先让运营稳定之后再考虑其他套餐

**Comment by ysd1123** [comment]
> 这个套餐对标的是每 GB 为 0.1 元，差不多是主流机场的中位数，然而前期收入依然不可观

想象不出来一个月代理100g以上的大佬都把代理拿来干嘛用(ಥ_ಥ)

**Comment by ysd1123** [comment]
> 不确定会不会提供月付套餐，可能会从季付开始。还是区分个人用户和多人用户，前期就不打算出其他的套餐，先让运营稳定之后再考虑其他套餐

可以先开个小调查问一下老用户的需求怎样？看下人数大概有多少

**Comment by kallydev** [comment]
> 可以先开个小调查问一下老用户的需求怎样？看下人数大概有多少

可以

**Comment by kallydev** [comment]
> 选高配套餐的大佬难道还会在意月付还是季付嘛？

也有人觉得年付不够，直接续了 4 年。按目前趋势看，这就是理财大佬

**Comment by ysd1123** [comment]
不清楚酸奶云的用户量是业内的多少，人少的话低配套餐好像挺亏的，我要后悔死了...虽然我确实挺希望有个低配套餐的，目前需求就这样

**Comment by ysd1123** [comment]
搜集一下各种方案，做个调查，算下成本，看下行不行

**Comment by kallydev** [comment]
![image](https://user-images.githubusercontent.com/36319157/79206903-95a1c580-7e72-11ea-9589-f3491d579432.png)

**Comment by ysd1123** [comment]
每个价位的配置都一样？  
我还是比较关心共享套餐是怎样的qwq（

**Comment by kallydev** [comment]
> 我还是比较关心共享套餐是怎样的qwq（

目前除了数据量不同也没想到其他的

**Comment by ysd1123** [comment]
> 目前除了数据量不同也没想到其他的

简单点的计价方式我觉得挺好的，又多又杂的了用户看了搞不懂，成本也不便于计算

**Comment by kallydev** [comment]
暂时原价不变
